from . import start
from . import manualdata
from . import update_application
from . import about
from . import web_server
from . import help
from . import echo
from . import update_menu
from . import application
