from aiogram.dispatcher.filters.state import StatesGroup, State


class PersonalData(StatesGroup):
    id_user = State()
    chat_id_user = State()
    phone = State()
    secret_code = State()
    document = State()
    birth_date = State()
    token = State()
    refreshToken = State()
    new_token = State()
    first_name = State()
    last_name = State()
    avatar = State()
    haveApplicationForm = State()
    haveApplied = State()
    haveEducation = State()
    reset_password = State()
    info = State()
    formatted_birth_date = State()
    application_id = State()
    birth_country = State()
    birth_country_id = State()
    birth_place = State()
    citizenship = State()
    gender = State()
    photo = State()
    pin = State()
    docgiveplace = State()
    docgiveplaceid = State()
    datebegin = State()
    dateend = State()
    application_src = State()
    which_level_need = State()
    country_id = State()
    country_name_uz = State()
    country_name_ru = State()
    country_name_en = State()
    region_id = State()
    region_name_uz = State()
    region_name_ru = State()
    region_name_en = State()
    district_id = State()
    address = State()
    father_name = State()
    father_phone = State()
    mother_name = State()
    pinfl_birth_country = State()
    pinfl_birth_country_id = State()
    created_at = State()
    pinfl_user_education = State()
    user_education = State()
    certifications = State()
    country_search = State()
    transfer_edu_name = State()
    transfer_direction_name = State()
    current_course = State()
    transcript = State()
    birth_date_new = State()
    document_new = State()


class EducationData(StatesGroup):
    education_id = State()
    region_id = State()
    district_id = State()
    institution_name = State()
    file_diploma = State()
    file_size = State()
    file_sertificate = State()
    type_certification = State()
    has_sertificate = State()
    get_certificate = State()
    certificate_type = State()
    file_size_sertificate = State()
    has_application = State()
    degree_id = State()
    degre_name = State()
    direction_id = State()
    direction_name = State()
    education_type = State()
    education_name = State()
    education_lang_id = State()
    education_lang_name = State()
    tuition_fee = State()
    menu = State()
    country_search = State()
    transfer_education_name = State()
    transfer_direction_name = State()
    which_course_now = State()
    country_id = State()
    country_name_uz = State()
    country_name_ru = State()
    country_name_en = State()
    file_diploma_transkript = State()
    work_experience = State()


class Account(StatesGroup):
    delete_account = State()


class ManualPersonalInfo(StatesGroup):
    personal_info = State()
    image = State()
    lastname = State()
    firstname = State()
    thirdname = State()
    document = State()
    birthdate = State()
    pin = State()
    gender = State()
    birthplace = State()
    extranumber = State()
    email = State()


class ManualEducationInfo(StatesGroup):
    education_type = State()
    region_id = State()
    district_id = State()
    institution_name = State()
    diploma = State()
    sertificate = State()
    type_certification = State()


class UpdateMenu(StatesGroup):
    lastname = State()
    firstname = State()
    thirdname = State()
    document = State()
    birthdate = State()
    pin = State()
    gender = State()
    birthplace = State()
    extranumber = State()
    email = State()
    birth_country = State()
    birth_country_id = State()
    birth_date = State()
    birth_place = State()
    citizenship = State()
    extra_phone = State()
    first_name = State()
    last_name = State()
    avatar = State()


class UpdateEducation(StatesGroup):
    education_type = State()
    region_id = State()
    district_id = State()
    institution_name = State()
    diploma = State()
    sertificate = State()
    type_certification = State()
    education_id = State()
    new_district_id = State()
    file_diploma = State()
    certificate_type = State()
    get_certificate = State()

